---
title: "About Page"
author: "Morgan Booker"
date: "10/17/2019"
output: html_document
---

### The Show

Criminal Minds is a popular procedural crime drama television series that airs on CBS and is about to debut its fifteenth and final season. The show follows a group of behavioral profilers in the FBI's Behavioral Analysis Unit (BAU) as they investigate the country's most-twisted criminal minds through criminal profiling. Criminal Minds is a hit show that has captured the American public's fascination with sensational crimes and the fourteen seasons that have aired have not disappointed in their content.

### The Crimes

Throughout the fourteen seasons, the BAU team has dealt with a wide variety of crimes and criminals including serial killers, arsonists, kidnappers, and domestic terrorists to name a few. Some stories featured on the show are based on true stories, which is possibly why this show has fascinated so many viewers for so long and has lead to multiple spin off shows. In most (but not all) episodes, the team captures the killer, either dead or alive.

### The Recurring Elements

Most episodes of the show feature some important recurring elements, this section will list a few that are relevant to this analysis.

* __The Team__: The key players of the BAU team include: Jason Gideon (Seasons 1-3), David Rossi, Aaron "Hotch" Hotchner (Seasons 1-12), Derek Morgan (Seasons 1-11), Spencer Reid, Emily Prentiss, Jennifer "JJ" Jareau, and Penelope Garcia. Major recurring team members have included: Elle Greenaway (Seasons 1-2).
* __The Capture__: Most episodes feature the capture or death of the suspect.
* __Buzzwords__: Each episode, there are a lot of key words or phrases that we hear. Some examples include "unsub" (unknown subject), "profile", "serial killer", "sadist", and "trophy".

### The Project

This project is a script analysis of the first five season of Criminal Minds, and has three main aspects to it.

#### General Overview

The General Overview section of the project aims to give a general overview of the data to show off some cool features found when analyzing the episode and script characteristics of the first five seasons. Some areas of focus include tracking the frequency of key buzzwords and character names over the five seasons, looking at the types of criminals the BAU team faces, how many times the criminal is caught, and the gender of the criminal.

#### Word Cloud

The Word Cloud section aims to give a more interactive version of word frequency across the first five seasons by allowing explorers of this project to play around with a wordcloud that tracks the frequency of buzzwords and character names throughout the first five seasons.

#### Criminal Analysis

The Criminal Analysis section aims to look at some of the recurring elements of Criminal Minds episodes explored in previous parts of the project and see how they interact with whether or not the criminal was caught at the end of the episode. For example, are we able to see a clear trend between word frequency and the outcome of the episode? If the word "unsub" is said often in an episode, will a pattern emerge that suggests that the criminal is more likely to be caught? This section aims to tackle questions like these to see if there are any cool trends we can unmask and reveal.

### The Data

I gathered the scripts for the first five seasons of the show from [Springfield! Springfield!](https://www.springfieldspringfield.co.uk/episode_scripts.php?tv-show=criminal-minds). I gathered the data about creative elements of the show (i.e. whether the criminal was caught, type of criminal, gender, etc.) from the [Criminal Minds Wiki](https://criminalminds.fandom.com/wiki/Criminal_Minds_Wiki) and constructed my own dataframe from the information found.

### Github Repo

The github repo with all the code for this project can be found [here](https://github.com/morganbooker/criminal_minds_analysis).

### About Me

My name is Morgan Booker and I am a senior at Harvard College studying statistics and psychology. If you would like to know more about me, my project, or other work I've done, feel free to check out my [github profile](https://github.com/morganbooker) or [email](mailto::morgan_booker@college.harvard.edu) me.

### Special Thanks
- David Kane and all the wonderful GOV 1005 staff
- Jeff Davis for creating the amazing show that is the basis of this project
- All the real-life crime fighters making the world a safer place
