---
title: "caught_character_season"
author: "Morgan Booker"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fs)
library(tm)
library(rvest)
library(janitor)
library(memoise)
library(tidytext)
library(wordcloud)
library(tidyverse)
library(RColorBrewer)
```

```{r data}
cm_words_bau <- cm_words %>% 
  filter(word %in% bau) %>% 
    mutate(word = case_when(
    word == "spencer" | word == "spence" | word == "reid" ~ "Spencer Reid",
    word == "derek" | word == "morgan" ~ "Derek Morgan",
    word == "aaron" | word == "hotch" | word == "hotchner" ~ "Aaron Hotchner",
    word == "david" | word == "dave" | word == "rossi" ~ "David Rossi",
    word == "jason" | word == "gideon" ~ "Jason Gideon",
    word == "emily" | word == "prentiss" ~ "Emily Prentiss",
    word == "jennifer" | word == "jj" | word == "jareau" ~ "Jennifer Jareau",
    word == "penelope" | word == "garcia" ~ "Penelope Garcia",
    word == "elle" | word == "greenaway" ~ "Elle Greenaway"
  ))
```


```{r season 1}
    
ccs_s1 <- cm_words_bau %>%
  select(episode, word, caught, alive, season) %>% 
  filter(season == "Season 1") %>% 
  group_by(episode, caught) %>% 
  count(word, sort = TRUE) %>% 
  drop_na() %>% 
  
  ggplot(aes(x = word, y = n, fill = caught)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(x = "Character Name",
       y = NULL)

write_rds(ccs_s1, "ccs_s1.rds")

```

```{r season 2}

ccs_s2 <- cm_words_bau %>%
  select(episode, word, caught, alive, season) %>% 
  filter(season == "Season 2") %>% 
  group_by(episode, caught) %>% 
  count(word, sort = TRUE) %>% 
  drop_na() %>% 
  
  ggplot(aes(x = word, y = n, fill = caught)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(x = "Character Name",
       y = NULL)

```

```{r season 3}

ccs_c3 <- cm_words_bau %>%
  select(episode, word, caught, alive, season) %>% 
  filter(season == "Season 3") %>% 
  group_by(episode, caught) %>% 
  count(word, sort = TRUE) %>% 
  drop_na() %>% 
  
  ggplot(aes(x = word, y = n, fill = caught)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(x = "Character Name",
       y = NULL)

```

```{r season 4}

ccs_s4 <- cm_words_bau %>%
  select(episode, word, caught, alive, season) %>% 
  filter(season == "Season 4") %>% 
  group_by(episode, caught) %>% 
  count(word, sort = TRUE) %>% 
  drop_na() %>% 
  
  ggplot(aes(x = word, y = n, fill = caught)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(x = "Character Name",
       y = NULL)

```

```{r season 5}

ccs_s5 <- cm_words_bau %>%
  select(episode, word, caught, alive, season) %>% 
  filter(season == "Season 5") %>% 
  group_by(episode, caught) %>% 
  count(word, sort = TRUE) %>% 
  drop_na() %>% 
  
  ggplot(aes(x = word, y = n, fill = caught)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(x = "Character Name",
       y = NULL)

```

