---
title: "Milestone 3: Script Analysis"
author: "Morgan Booker"
date: "10/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview of Data and Project Plan
For my project, I am planning on doing a script analysis of crime-related TV shows and movies. Ideally, I want to analyze the contents of scripts for famous crime movies and a crime-focused TV show (Criminal Minds on CBS) to see what characteristics of the movie or the episode are related to the outcome. For example, with Criminal Minds, I could look at a buzzword like "unsub" (which stands for unknown subject) and see if the amount of times this is said in an episode has any relation to if they catch the criminal. I want to look at trends like that and be able to answer key questions like this through graphics. For now, I am extending my project to both Criminal Minds and famous crime movies, but this may make the scope of my project too big, so later on I may choose to focus on just Criminal Minds (which has 14 seasons worth of episodes) or just crime movies; this is a decision I will make later on as I do more exploratory analysis and play around with the data as I figure out cool things I could do with my project.

My data comes from two main sources. For the TV show scripts, I found a website with the scripts of all episodes of Criminal Minds (link: https://www.springfieldspringfield.co.uk/episode_scripts.php?tv-show=criminal-minds) and for the movie scripts, I found a website that contains a variety of publicly available famous crime movie scripts (link: https://www.simplyscripts.com/genre/crime-scripts.html), including Gangs of New York and The Godfather triology among other films. The Criminal Minds scripts only have the spoken words detailed and do not include which characters spoke them or any scenic notes whereas there is more variety in the movie scripts with some having just written dialogue, some having written dialogue the characters who spoke them, and some having dialogue, characters, and scenic notes. I think it might be interesting to be able to include some analysis of the amount of times different characters say different buzzwords, so I may continue my data search by either trying to find Criminal Minds scripts with more detail, switching to a different crime show where I can find scripts with these details, or only focusing on movie scripts with these details.

So far, I have only worked with one script from online (the pilot script for Criminal Minds, named cm_1x01.txt in this repo in case anyone wants to look at it) because I wanted to try out and test different approaches to dealing with this type of data before downloading a bunch of material since I haven't done anything with scripts outside of the one Datacamp chapter (which I will definitely be reviewing). So far, I have mostly focused on loading in the script and making it into a dataframe. First, I made a dataframe where each line in the script was a different row, then I wanted to be able to break each line up into a single word because I thought that might be helpful in filtering out the amount of times the word was said, so I found the tidytext package from Google, and used the unnest_tokens() function to achieve this. After doing this, I counted the amount of times a couple of key words from the show were said ("Unsub", "Reid", "Morgan" (two of the main characters)). One thing I haven't done yet that is really important is to check over the dataset looking for any obvious problems with this approach (i.e. are there some words that got parsed incorrectly, etc.), so that is something I will focus on next along with also continuing to consider other approaches to handling this type of data.

Another thing I would definitely like to include in my project is tons of visualizations. Particularly, I know that I want to include visualizations of the buzzwords and how many times they are spoken in an episode or season or by a character in an episode or a season (for Criminal Minds) or in the movie. It might also be cool to do a word cloud like Tate did in her Game of Thrones final project as well.